### ISSUE TITLE
MacOS X

### ISSUE THREAD

**Issue by m0rph90** [MicrosoftDocs/visualstudio-docs.de-de#14]
Euch ist schon bewusst, dass ihr auch eine Mac OS Version habt....

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 00e3e8d0-48c3-3df6-8aeb-acd9624ffcd5
* Version Independent ID: 13f5da30-9f06-236f-4110-b6a172c52d1f
* Content: [Gewusst wie: Verwalten des Zeilenumbruchs im Editor - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/ide/reference/how-to-manage-word-wrap-in-the-editor?view=vs-2017)
* Content Source: [docs/ide/reference/how-to-manage-word-wrap-in-the-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/ide/reference/how-to-manage-word-wrap-in-the-editor.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #1513](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1513) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #1512](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1512) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hallo, @m0rph90 

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation. 
Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/visualstudio-docs/issues/1512 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
