### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by mohaplus** [MicrosoftDocs/visualstudio-docs.de-de#4]
I have try The QuickInfo in vs 2015, but it does not work in debug mode , I want to know how to resolve it,thanks

**Comment by CeciAc** [comment]
Hello, @mohaplus ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button **"Give Product Feedback"** at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
