### ISSUE TITLE
Übersetzung Deutsch

### ISSUE THREAD

**Issue by ngzero** [MicrosoftDocs/visualstudio-docs.de-de#44]
Sehr schlechte automatische Übersetzung.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6b417a6f-2527-9ec4-7e00-a0ce8e55f997
* Version Independent ID: d250f719-b8d7-7b03-d883-968e0b961d49
* Content: [Codemetrik berechnen - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/code-quality/code-metrics-values?view=vs-2017)
* Content Source: [docs/code-quality/code-metrics-values.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/code-quality/code-metrics-values.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@JasonCard FYI (poor machine translation of this topic).

**Comment by CeciAc** [comment]
Hallo, @ngzero 

Vielen Dank für Ihr Feedback. Die betroffene Seite wurde maschinenübersetzt. Daher kann es sein, dass der Inhalt nicht immer verständlich ist. Wir haben vor Kurzem die Option „Read in English“ (Auf Englisch lesen) rechts hinzugefügt, sodass Sie zur englischen Version wechseln können, ohne die Spracheinstellungen ändern zu müssen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team

**Comment by JasonCard** [comment]
@ngzero @gewarren 
Thank you for letting me know of your feedback!
I will keep this in mind for future consideration.
