### ISSUE TITLE
Which Outlook Version?

### ISSUE THREAD

**Issue by LarsMeyer311** [MicrosoftDocs/visualstudio-docs.de-de#50]
I downloaded Microsoft Office Developer Tools Preview 2 for Visual Studio 2015. And tried this tutorial with Outlook 2010. Got the error "Cannot debug or run Word AddIn because the required version of Microsoft Office is not installed".  Is there any chance to use this tutorial with any old Outlook version?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bd2cccf4-e8b1-aa69-b3ae-50d27b2a4d50
* Version Independent ID: 9c3a644a-f267-4092-24be-2566788e7500
* Content: [Exemplarische Vorgehensweise: Erstellen des ersten VSTO-Add-Ins für Outlook - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/vsto/walkthrough-creating-your-first-vsto-add-in-for-outlook?view=vs-2019#feedback)
* Content Source: [docs/vsto/walkthrough-creating-your-first-vsto-add-in-for-outlook.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/vsto/walkthrough-creating-your-first-vsto-add-in-for-outlook.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by CeciAc** [comment]
Hello, @LarsMeyer31

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
