### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by GangstaSunny** [MicrosoftDocs/visualstudio-docs.de-de#51]
"Wenn Sie vorhanden" sollte in "Wenn Sie vorhaben" geändet werden.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b3f3b693-ce79-749a-95cb-6d8d129a36af
* Version Independent ID: ea63dbbf-22ba-26fb-0ed8-da83b818b5e3
* Content: [Verbessern der Leistung, wenn Visual Studio langsam ist](https://docs.microsoft.com/de-de/visualstudio/ide/optimize-visual-studio-performance?view=vs-2019#feedback)
* Content Source: [docs/ide/optimize-visual-studio-performance.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/ide/optimize-visual-studio-performance.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by CeciAc** [comment]
Hallo, @GangstaSunny 

Vielen Dank für Ihr Feedback. 

Ihre Kommentare werden aktuell von uns geprüft. Wir melden uns bald bei Ihnen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @GangstaSunny
  
Vielen Dank für Ihr Feedback. 
unsere Sprachexperten haben sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/visualstudio/ide/optimize-visual-studio-performance?view=vs-2019#feedback

Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
