### ISSUE TITLE
COM Exeption

### ISSUE THREAD

**Issue by Koschnag** [MicrosoftDocs/visualstudio-docs.de-de#54]
Outlook.ContactItem newContact = (Outlook.ContactItem)
        this.Application.CreateItem(Outlook.OlItemType.olContactItem);

Wird nicht ausgeführt. Es kommt zu einer Expeption. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0e3823c7-a926-c6d1-83ba-93b231bf6aed
* Version Independent ID: 3c0b5d1d-5a42-2454-6c4c-09390ac7678e
* Content: [Vorgehensweise: Programmgesteuertes Hinzufügen eines Eintrags zu Outlook-Kontakten - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/vsto/how-to-programmatically-add-an-entry-to-outlook-contacts?view=vs-2019#feedback)
* Content Source: [docs/vsto/how-to-programmatically-add-an-entry-to-outlook-contacts.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/vsto/how-to-programmatically-add-an-entry-to-outlook-contacts.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by CeciAc** [comment]
Hallo, @Koschnag 

vielen Dank für Ihren Beitrag. Unser Team kann nur Feedback beantworten, das sich auf die Dokumentation bezieht. 
Übermitteln Sie Feedback zu Produkten über die Schaltfläche „Feedback zu Produkten“ ganz unten auf der Dokumentationsseite. 

Wenn Sie Feedback zur Dokumentation haben, können Sie dieses gerne hier übermitteln. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
