### ISSUE TITLE
Doesn't provide useful information

### ISSUE THREAD

**Issue by bjepsen** [MicrosoftDocs/visualstudio-docs.de-de#55]
I came here to learn how to cope with the error "Need help to construct object". But this page doesn't say anything about it. So like always: You have tons of non-relevant information but are missing the relevant information. I wonder how your brains must be wired to perform so utterly bad. I think, MS should return to recruiting specialists.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: be15faaa-351a-cffe-eabf-60d2173f53b8
* Version Independent ID: 9ba27f95-94af-9108-8233-6c9c70fc3c22
* Content: [Dynamische symbolische Ausführung - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/test/intellitest-manual/input-generation?view=vs-2019#feedback)
* Content Source: [docs/test/intellitest-manual/input-generation.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/test/intellitest-manual/input-generation.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by CeciAc** [comment]
Hello, @bjepsen

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
