### ISSUE TITLE
"Bei jeder Änderung, die Sie an app.tsx vornehmen, müssen Sie den Webpack-Befehl erneut ausführen."

### ISSUE THREAD

**Issue by HannsMartinSlayer** [MicrosoftDocs/visualstudio-docs.de-de#56]
Ist das ernst gemeint? Das hat doch die Eleganz eines Zündschlosses im Kofferraum. Lässt sich das nicht automatisieren?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c4b0ea28-4a31-a3ea-fa5f-c32d5c72d4bd
* Version Independent ID: 31bd064b-51eb-5505-986e-2c7148784085
* Content: [Erstellen von Node.js- und Express-Apps - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2019#feedback)
* Content Source: [docs/javascript/tutorial-nodejs-with-react-and-jsx.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/javascript/tutorial-nodejs-with-react-and-jsx.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by CeciAc** [comment]
Hallo, @HannsMartinSlayer 

vielen Dank für Ihren Beitrag. Unser Team kann nur Feedback beantworten, das sich auf die Dokumentation bezieht. 
Übermitteln Sie Feedback zu Produkten über die Schaltfläche „Feedback zu Produkten“ ganz unten auf der Dokumentationsseite. 

Wenn Sie Feedback zur Dokumentation haben, können Sie dieses gerne hier übermitteln. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
