### ISSUE TITLE
Code Metrics XML

### ISSUE THREAD

**Issue by mradckeIRT** [MicrosoftDocs/visualstudio-docs.de-de#59]
I would appreciate a comment on how to work with the Metrics.XML file generated via CI or commandline tools. How to evaluate against set thresholds for example.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 070043dc-013c-0e82-bb24-95a4bf2d8743
* Version Independent ID: 738fa065-17c1-6785-8029-bbf74d7b3e39
* Content: [Codemetrikfenster - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/code-quality/working-with-code-metrics-data?view=vs-2019#feedback)
* Content Source: [docs/code-quality/working-with-code-metrics-data.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/code-quality/working-with-code-metrics-data.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by srvbpigh** [comment]
Hello, @mradckeIRT
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @mradckeIRT 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
