### ISSUE TITLE
German link malformed

### ISSUE THREAD

**Issue by soelax** [MicrosoftDocs/visualstudio-docs.de-de#60]
Malformed translation of a link in German version
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: de8f3d05-2544-c058-390a-e891f884fa17
* Version Independent ID: 498f1db6-4ff2-b317-84df-3377eef4bb75
* Content: [Erweitern und Anpassen von Tool Windows - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/extensibility/extending-and-customizing-tool-windows?view=vs-2019)
* Content Source: [docs/extensibility/extending-and-customizing-tool-windows.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/extensibility/extending-and-customizing-tool-windows.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by soelax** [comment]
![image](https://user-images.githubusercontent.com/47345833/62999584-3583fb00-be6f-11e9-949d-bbd1e9f6d588.png)

**Comment by srvbpigh** [comment]
Hello, @soelax
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @soelax

Vielen Dank für Ihr Feedback. Die betroffene Seite wurde maschinenübersetzt. Daher kann es sein, dass der Inhalt nicht immer verständlich ist. Wir haben vor Kurzem die Option „Read in English“ (Auf Englisch lesen) rechts hinzugefügt, sodass Sie zur englischen Version wechseln können, ohne die Spracheinstellungen ändern zu müssen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
