### ISSUE TITLE
Zip appears to use backslashes as path separators

### ISSUE THREAD

**Issue by MichaCo** [MicrosoftDocs/visualstudio-docs.de-de#61]
Seems the ZipDirectory task creates invalid zip files with backslash which causes warnings and issues on Linux.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4c2cbd60-5d56-af4f-b196-4c9f190a1586
* Version Independent ID: 6408870a-85cd-428c-5ede-2338804481d6
* Content: [ZipDirectory-Aufgabe - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/msbuild/zipdirectory-task?view=vs-2019)
* Content Source: [docs/msbuild/zipdirectory-task.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/msbuild/zipdirectory-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by srvbpigh** [comment]
Hello, @MichaCo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @MichaCo

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
