### ISSUE TITLE
How to use this container behind a corporate proxy?

### ISSUE THREAD

**Issue by Abassina** [MicrosoftDocs/visualstudio-docs.de-de#62]
After Building the container like the description i get always during msbuild of my solutionfile the error. 

C:\my-vol\g5\503886ESWTest_ExtendedTp.vcxproj(31,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Micr
osoft.Cpp.Default.props" was not found. Confirm that the path in the &lt;Import&gt; declaration is correct, and that the file exists on disk.

I need help...

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Installieren von Visual Studio Build Tools in einem Container](https://docs.microsoft.com/de-de/visualstudio/install/build-tools-container?view=vs-2019#feedback)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by srvbpigh** [comment]
Hello, @Abassina
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Abassina

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
