### ISSUE TITLE
Error: Das Paket 'Microsoft.VisualStudio.Component.AzureDevOps.OfficeIntegration' wurde nicht erkannt.

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/visualstudio-docs.de-de#64]
When trying to install some components regarding to this list I get an error:

vs_community__818795694.1537480254.exe --layout D:\SQLServer_Setup_diverse\vslayout --add Microsoft.VisualStudio.Component.CoreEditor --add Microsoft.VisualStudio.Workload.Data --add Microsoft.VisualStudio.Workload.DataScience --add Microsoft.VisualStudio.Workload.Python --add Component.GitHub.VisualStudio --add Microsoft.Component.HelpViewer --add Microsoft.VisualStudio.Component.AzureDevOps.OfficeIntegration --add Microsoft.VisualStudio.Component.Git --includeRecommended --lang en-US

Tolle Fehlermeldung:
Visual Studio Setup Command Line Utility, version 1.18.1049.33485
Copyright (C) Microsoft Corporation. All rights reserved.

Download of 'https://aka.ms/vs/15/release/channel' succeeded using engine 'WebClient'
Download of 'https://download.visualstudio.microsoft.com/download/pr/82e3dcda-e8a0-44e4-8860-eb93a12d4e80/61c5d0ed852e311c8fd6a62627fcb326da6aa79028b40ae25ee062da3c33791b/VisualStudio.vsman' succeeded using engine 'WebClient'
Catalog load operation correlation: {"id":"e3e60385-1915-4031-8ea6-a6e1717ea8dc"}
Layout operation correlation: {"id":"d59730ed-a56e-4cb6-abf9-3ba824cd7af5"}
Planning 'Layout' operation
Error: Das Paket 'Microsoft.VisualStudio.Component.AzureDevOps.OfficeIntegration' wurde nicht erkannt.
Error: Failed to plan for Layout.
Error: Einrichtung mit Fehlern abgeschlossen.
Error: Das Paket 'Microsoft.VisualStudio.Component.AzureDevOps.OfficeIntegration' wurde nicht erkannt.
Drücken Sie eine beliebige Taste, um fortzufahren...

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4891ebc9-fdea-c376-94f6-17295ca275d7
* Version Independent ID: ccc61918-cc18-a7ff-cc6c-8659d6c9c78a
* Content: [Workload- und Komponenten-IDs in Visual Studio Community](https://docs.microsoft.com/de-de/visualstudio/install/workload-component-id-vs-community?vs-2019&view=vs-2019)
* Content Source: [docs/install/workload-component-id-vs-community.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/install/workload-component-id-vs-community.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @aisbergde 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by aisbergde** [comment]
I think this bug is related to the documentation and not to the product. The module should not be listed in the documentation if it is not available. Documentation should represent the reality but not the reality should be changed to match the documentation.

**Comment by CeciAc** [comment]
Hello, @aisbergde

 Please review the status of the issue here - XXX.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @aisbergde 

Please check the answer given by the writer of the document here https://github.com/MicrosoftDocs/visualstudio-docs/issues/4054

> I took a look at this yesterday and I believe the problem is that the customer tried to run a Visual Studio Community 2017 bootstrapper (vs_community.exe) against a Visual Studio Community 2019 manifest. The giveaway here is when they report using "https://aka.ms/vs/15/release/channel". The version "15" is associated with Visual Studio 2017, where the version "16" is associated with Visual Studio 2019.
> 
> If you check both the en-us copy and the de-de copy of the Workload and Component IDs page for Visual Studio Community 2017, you see that the "Microsoft.VisualStudio.Component.AzureDevOps.OfficeIntegration" component is not listed on either of them. (It is, however, listed on the Workload and Component IDs page for Visual Studio Community 2019.)

Kind regards,
Microsoft DOCS International Team

**Comment by aisbergde** [comment]
As I answered on another item:
I followed the instruction step by step and the download link for the bootstrapper pointed to vs_community__818795694.1537480254.exe
If this is the wrong version then the instruction should be corrected and the link should point to the right version of VS.
