### ISSUE TITLE
You should add information how to not execute the line but to add a new line to get the "..."

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/visualstudio-docs.de-de#65]
at 4:
Beim Schreiben einer mehrzeiligen Anweisung, wie einer Funktionsdefinition, wird im interaktiven Fenster die Python-Eingabeaufforderung ... zum Fortsetzen der Zeilen angezeigt, die im Gegensatz zur Befehlszeilen-REPL automatischen Einzug bietet:

You should add information how to not execute the line but to add a new line to get the "..."
For example "press Ctrl-Enter instead of Enter to ..."

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 781f50f5-dc28-6776-71e9-c3cfbcb87ff4
* Version Independent ID: 8d7da87c-b17d-d3d2-aacd-3242e632b652
* Content: [Tutorial „Python in Visual Studio“, Schritt 3: Interaktive REPL](https://docs.microsoft.com/de-de/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl?view=vs-2019)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by aisbergde** [comment]
The hint regarding this, which is places after step 7, should be placed on step 4, because people will go step by step.

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #4037](https://github.com/MicrosoftDocs/visualstudio-docs/issues/4037) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
Hello, @aisbergde ,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/4037.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
