### ISSUE TITLE
wrong instructions in step 7, missing: need to copy also the definition of make_dot_string to the interactive window

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/visualstudio-docs.de-de#66]
if following the instruction in step 7 it will not work:
only bring the import part to the interactive Window and then to call the function will not work.

In the instruction you should write, that not only the import and from needs to be transfered to the interactiv window, but also the definition of make_dot_string.

The screenshot is write, only the instruction is missing a part.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 781f50f5-dc28-6776-71e9-c3cfbcb87ff4
* Version Independent ID: 8d7da87c-b17d-d3d2-aacd-3242e632b652
* Content: [Tutorial „Python in Visual Studio“, Schritt 3: Interaktive REPL](https://docs.microsoft.com/de-de/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl?view=vs-2019)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #4036](https://github.com/MicrosoftDocs/visualstudio-docs/issues/4036) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
Hello, @aisbergde 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/4036.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
