### ISSUE TITLE
Links für Visual Studio-Bootstrappers => alte Version von VS (2017 statt 2019)

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/visualstudio-docs.de-de#67]
Ich bin die hier angegebene Anleitung durchgegangen
Schritt 1: Herunterladen des Visual Studio-Bootstrappers
Wenn man nun Visual Studio-Community	vs_community.exe lädt, bekommt man
vs_community__818795694.1537480254.exe
Das ist laut Microsoft aber nicht Visual Studio 2019 sondern eine ältere Version: 2017
Das führt zu Problemen:
https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/64
https://github.com/MicrosoftDocs/visualstudio-docs/issues/4054
Vielleicht gab es noch andere Cases. Jetzt sind sie alle geschlossen, der Link hier ist aber immer noch falsch (Keine Ahnung, ob das nur im Deutschen so ist, daher schreibe ich jetzt mal auf Deutsch, da das im Englischen Original behoben worden sein soll)

Die Erwartung an die Dokumentation wäre, dass man sie Schritt für Schritt nachvollziehen kann und dann auch einen Installer für Visual Studio 19 erstellen kann. Vielleicht sollte man für die Bootstraper-Downloads explizit die Version mit angeben, damit man schon am Namen der heruntergeladenen Datei erkennt, was das nun für eine Version ist. Wie soll ein normaler Anwender das an so einem Namen erkennen? vs_community__818795694.1537480254.exe
Dann zieht man das alles durch, verbraucht eine Menge Zeit zum Erstellen, muss das irgendwie auf einen Server bekommen, GB an Daten, und am Ende hat man dann da ein Visual Studio 2107 installiert. Sehr frustrierend.

Es ist schon schwer genug, dass man sich einen Installer auf so komplizierte Art und Weise selbst zusammenstellen muss. Da ist es dann schon blöd, wenn man Ende immer noch nicht weiß, wie man sich nun einen Installer für VS 2019 herstellen kann.

Auf vielen Servern ist Internet limitiert, da geht es nur mit offline Installern.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Erstellen einer Offlineinstallation - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #4073](https://github.com/MicrosoftDocs/visualstudio-docs/issues/4073) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hallo, @aisbergde

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation. 
Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/visualstudio-docs/issues/4073
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
