### ISSUE TITLE
Missing latest options from v15.7

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/visualstudio-docs.de-de#7]
This page is missing a bunch of options I see in Visual Studio 15.7 on the same Options page. Please add the corresponding documentation here. This is particularly important for translated versions of Visual Studio 2017 as the translation is often misleading and poor.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c03f0366-9eb0-a623-57dc-23c34ca5c73a
* Version Independent ID: 4682db7d-610f-2cf1-523b-34fdc10a016f
* Content: [Optionen, Text-Editor, Allgemein](https://docs.microsoft.com/de-de/visualstudio/ide/reference/options-text-editor-general?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DDE-DE%26k%3Dk(VS.ToolsOptionsPages.Text_Editor.General)%26rd%3Dtrue)
* Content Source: [docs/ide/reference/options-text-editor-general.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/ide/reference/options-text-editor-general.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by CeciAc** [comment]
Hi @SetTrend 
Thank you for your feedback.

**Can you please specify which are these missing options you mention so we can investigate it?**

Kind regards,
Microsoft DOCS International Team

**Comment by SetTrend** [comment]
Sure, here they are:

![text-editor allgemein](https://user-images.githubusercontent.com/9283914/40988028-5ae8d0fe-68ea-11e8-9fd3-4002e0984c3f.png)

![text-editor alle sprache scrollleisten](https://user-images.githubusercontent.com/9283914/40988036-5e342790-68ea-11e8-9af8-1241958791b2.png)

![text-editor basic erweitert](https://user-images.githubusercontent.com/9283914/40988039-616c00ea-68ea-11e8-93f7-2b1b551acfaa.png)

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #1090](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1090) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @SetTrend,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here https://github.com/MicrosoftDocs/visualstudio-docs/issues/1090

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
