### ISSUE TITLE
Nur Code ohne Form wird in der Designer-View angezeigt

### ISSUE THREAD

**Issue by eifcgn24** [MicrosoftDocs/visualstudio-docs.de-de#70]
Hallo,
ich habe das "Erste Schritte" Tutorial absolviert und mir die Forms für die Desktop Entwicklung im Visual Studio runtergeladen. Im ersten Programm war die Designer Form noch zu sehen. Aber jetzt startet Visual Studio immer ohne Form. Nur die Code View wird angezeigt.  UMSCHALT + F7 öffnet die Code View. Wie kriegt man die Form wieder angezeigt?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0b7e2601-1fe4-228c-bde4-e29e52c8f7b9
* Version Independent ID: f5e06a1c-63aa-75fb-8398-0cb32db19677
* Content: [Schritt 3: Festlegen der Formulareigenschaften - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/ide/step-3-set-your-form-properties?view=vs-2019#feedback)
* Content Source: [docs/ide/step-3-set-your-form-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/ide/step-3-set-your-form-properties.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by srvbpigh** [comment]
Hello, @eifcgn24
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @eifcgn24

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation. 
Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/visualstudio-docs/issues/4207
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team

**Comment by maitrey2** [comment]
Hello,

In step-3: set your form properties when I select Form1.Designer.cs, I don't see Text-font properties in Properties window. Please see attached.

![Capture](https://user-images.githubusercontent.com/32009645/67687241-694ec700-f96e-11e9-9871-1beade65321a.PNG)
