### ISSUE TITLE
Fehlermeldung PyLint

### ISSUE THREAD

**Issue by ERueffel** [MicrosoftDocs/visualstudio-docs.de-de#72]
Hallo zusammen. Habe alles gem. Anweisungen gemacht und bekomme hier folgende Fehlermeldung von PyLint. 
Die Verweisassemblys für Framework ".NETFramework,Version=v4.0" wurden nicht gefunden...
Das wird wahrscheinlich jedem so gehen, der nach dieser Anweisung vorgeht. Könnten Sie hier bitte veröffentlichen, wie man damit umgeht.
Gruss

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fb4711da-9ab9-0341-1c2e-03bc88930cc5
* Version Independent ID: c5119fdb-a5ad-0e64-2bd9-bfa983e1a4f7
* Content: [Tutorial „Python in Visual Studio“, Schritt 2: Schreiben und Ausführen von Code](https://docs.microsoft.com/de-de/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-02-writing-code?view=vs-2019#feedback)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-02-writing-code.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/python/tutorial-working-with-python-in-visual-studio-step-02-writing-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by srvbpigh** [comment]
Hello, @ERueffel
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @ERueffel 

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation. 
Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/visualstudio-docs/issues/4374
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
