### ISSUE TITLE
Unsinnige Bezeichnung

### ISSUE THREAD

**Issue by Sonfix** [MicrosoftDocs/visualstudio-docs.de-de#76]
Hallo,

auf dieser Seite, gibt es einige Unsinnige Bezeichnungen. Z.b. unter dem 2. Punkt: In der &lt;Projekt &gt; Eigenschaftenseiten Dialogfeld stellen Sie sicher, dass die Konfiguration Feld am oberen Rand des Fensters 
nastaven NA hodnotu 
Debuggen.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c922c9cf-4c0b-18fb-d1bd-afa4303db5fd
* Version Independent ID: 72b4a51f-b499-41b4-6d68-19c9deaf7e3f
* Content: [Vorgehensweise: Debuggen über ein DLL-Projekt - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/debugger/how-to-debug-from-a-dll-project?view=vs-2019#feedback)
* Content Source: [docs/debugger/how-to-debug-from-a-dll-project.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/debugger/how-to-debug-from-a-dll-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by srvbpigh** [comment]
Hello, @Sonfix
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hallo @Sonfix:

Vielen Dank für Ihren Beitrag. 

Beiträge zu Übersetzungsproblemen in maschinell übersetzten Inhalten werden zurzeit nicht akzeptiert. 

Wir schätzen Ihr Feedback und Ihre Vorschläge zu von Menschen übersetzten Inhalten. Diese werden verwendet, um die Engines für maschinelle Übersetzung zu trainieren. Mit der Zeit verbessern Ihre Beiträge also die Qualität menschlicher und maschineller Übersetzungen. 

Anhand des ms.translationtype-Metadatenwerts im Header einer Inhaltsdatei können Sie zwischen menschlicher und maschineller Übersetzung unterscheiden. Dabei steht „HT“ für menschliche Übersetzung und „MT“ für maschinelle Übersetzung. 

Vielen Dank für Ihre Unterstützung! 

Microsoft DOCS Global Experience Team
