### ISSUE TITLE
Funktioniert nicht...

### ISSUE THREAD

**Issue by shendayan** [MicrosoftDocs/visualstudio-docs.de-de#77]
Ich versuche aus dem Datenquellen-Fenster eine Tabelle in ein Formular zu ziehen, aber es passiert nichts. Ich kann so weder ein DataGridView erzeugen, noch einzelne Steuerelemente, wenn ich die Tabelle vorher auf Details gestellt habe. Keine Ahnung, woran es liegen kann, aber ich bin nicht zu blöde für Drag & Drop.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2de1af78-290b-4177-65ed-d8fc91d38f64
* Version Independent ID: 3d0ac0a3-8ef2-645b-0528-2176852b80c4
* Content: [Binden von Windows Forms-Steuerelementen an Daten - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/data-tools/bind-windows-forms-controls-to-data-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/data-tools/bind-windows-forms-controls-to-data-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/data-tools/bind-windows-forms-controls-to-data-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by srvbpigh** [comment]
Hello, @shendayan
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #4707](https://github.com/MicrosoftDocs/visualstudio-docs/issues/4707) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hallo, @shendayan,  

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation.  

Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/visualstudio-docs/issues/4707.  

Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.   

Mit freundlichen Grüßen  
das Microsoft DOCS International Team
