### ISSUE TITLE
Debugging not working

### ISSUE THREAD

**Issue by RBates2020** [MicrosoftDocs/visualstudio-docs.de-de#78]
You say: Wechseln Sie zum Fenster " Module " (Debuggen &gt; Windows &gt; Module), und überprüfen Sie, ob das Modul geladen ist.
And where is this Fenster "Module"? It's no wonder nobody ever answers if you can't even explain the simplest thing.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 95bc6d7e-2b58-4755-4411-c5f369011a6c
* Version Independent ID: d5710161-bc97-6d33-6c6b-77fc9cfe9c62
* Content: [Behandeln von Problemen mit Breakpoints im Debugger - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/debugger/troubleshooting-breakpoints?view=vs-2019#feedback)
* Content Source: [docs/debugger/troubleshooting-breakpoints.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/debugger/troubleshooting-breakpoints.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by srvbpigh** [comment]
Hello, @RBates2020
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hallo, @RBates2020,

vielen Dank für Ihren Beitrag. Unser Team kann nur Feedback beantworten, das sich auf die Dokumentation bezieht.  

Übermitteln Sie Feedback zu Produkten über die Schaltfläche „Feedback zu Produkten“ ganz unten auf der Dokumentationsseite.  

Wenn Sie Feedback zur Dokumentation haben, können Sie dieses gerne hier übermitteln.  

Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.   

Mit freundlichen Grüßen  

das Microsoft DOCS International Team

**Comment by SIH007GMail** [comment]
Ok I found the reason - Debugging - Window extends massively if you run the  code and then select Debugging - Window. Would be very helpful if that was mentioned in the documentation - I searched for hours!
