### ISSUE TITLE
Python Development Tools in Installation nicht mehr enthalten

### ISSUE THREAD

**Issue by ChristianGebhardt** [MicrosoftDocs/visualstudio-docs.de-de#80]
Ich hatte das Produkt vor einigen Monaten installiert und konnte "Python Development" auswählen und installieren. Jetzt wollte ich es auf einen neuen Rechner installieren und die Option gibt es einfach nicht mehr. Was muss ich installieren, dass ich die Funktionen weiter nutzen kann? Ich benötige das "Python native development tool" Paket.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b3dfab77-abe5-b079-1561-8ebd926f5cf8
* Version Independent ID: 2b799f56-7a98-83cb-5e18-c2be93cafd49
* Content: [Installieren von Python-Unterstützung - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/python/installing-python-support-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/python/installing-python-support-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/python/installing-python-support-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by srvbpigh** [comment]
Hello, @ChristianGebhardt
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hallo, @ChristianGebhardt,

vielen Dank für Ihren Beitrag. Unser Team kann nur Feedback beantworten, das sich auf die Dokumentation bezieht.  

Übermitteln Sie Feedback zu Produkten über die Schaltfläche „Feedback zu Produkten“ ganz unten auf der Dokumentationsseite.  

Wenn Sie Feedback zur Dokumentation haben, können Sie dieses gerne hier übermitteln.  

Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.   

Mit freundlichen Grüßen  

das Microsoft DOCS International Team

**Comment by ChristianGebhardt** [comment]
Hallo,

sind sind lustig. Offensichtlich stimmt die Dokumentation nicht mit dem
Produkt überrein. Damit sollte es schon für die Dokumentationsseite
relevant sein. Eine Dokumentation zu einem Produkt, das es nicht gibt,
macht ja wenig Sinn.

Viele Grüße

Christian Gebhardt

Am 24.02.2020 um 19:23 schrieb Ticiana Ciminari:
