### ISSUE TITLE
Leben Ohne Depperte Nachbaren 

### ISSUE THREAD

**Issue by christian7877** [MicrosoftDocs/visualstudio-docs.de-de#82]
XML

Kopieren
&lt;Project DefaultTargets="Compile"
    xmlns="http://schemas.microsoft.com/developer/msbuild/2003" &gt;

    &lt;PropertyGroup&gt;
        &lt;builtdir&gt;built&lt;/builtdir&gt;
    &lt;/PropertyGroup&gt;

    &lt;ItemGroup&gt;
        &lt;CSFile Include="*.cs" Exclude="Form2.cs"/&gt;

        &lt;Reference Include="System.dll"/&gt;
        &lt;Reference Include="System.Data.dll"/&gt;
        &lt;Reference Include="System.Drawing.dll"/&gt;
        &lt;Reference Include="System.Windows.Forms.dll"/&gt;
        &lt;Reference Include="System.XML.dll"/&gt;
    &lt;/ItemGroup&gt;

    &lt;Target Name="PreBuild"&gt;
        &lt;Exec Command="if not exist $(builtdir) md $(builtdir)"/&gt;
    &lt;/Target&gt;

    &lt;Target Name="Compile" DependsOnTargets="PreBuild"&gt;
        &lt;Csc Sources="@(CSFile)"
            References="@(Reference)"
            OutputAssembly="$(builtdir)\$(MSBuildProjectName).exe"
            TargetType="exe" /&gt;
    &lt;/Target&gt;
&lt;/Project

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 30273668-658c-d411-5b6d-7f58256bb0f3
* Version Independent ID: c8812ae3-0fb1-a30f-02dd-ebc2d28b9dc8
* Content: [Vorgehensweise: Ausschließen von Dateien vom Buildvorgang - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/msbuild/how-to-exclude-files-from-the-build?view=vs-2019#feedback)
* Content Source: [docs/msbuild/how-to-exclude-files-from-the-build.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/msbuild/how-to-exclude-files-from-the-build.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by srvbpigh** [comment]
Hello, @christian7877
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @christian7877 

Wir freuen uns über Ihren Kommentar und bemühen uns, Ihre Erfahrungen mit docs.microsoft.com zu verbessern. Wir benötigen jedoch weitere Informationen, um auf Ihr Feedback eingehen zu können. Können Sie uns bitte nähere Informationen geben und Ihren Kommentar erläutern? 

Mit freundlichen Grüßen 

Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hallo, @christian7877, 

Nochmals vielen Dank für Ihren Kommentar. 

Leider fehlen uns immer noch Informationen und wir können Ihr Feedback nicht bearbeiten. Wir schließen dieses GitHub-Problem jetzt, möchten Sie aber ermutigen, in Zukunft weiteres Feedback zu geben. 

Mit freundlichen Grüßen 

Microsoft DOCS International Team
