### ISSUE TITLE
druff druff druff

### ISSUE THREAD

**Issue by klausi13** [MicrosoftDocs/visualstudio-docs.de-de#86]
[Hier Feedback eingeben]

Habt ihr was zum lachen
![26b60f3d30edc4f22d2e9e9f265e0597](https://user-images.githubusercontent.com/65920526/85921765-d197d480-b87e-11ea-8657-b98c75d5f5fd.gif)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f307022f-0b34-372f-2185-b61227c110a7
* Version Independent ID: feabd94b-8396-4c5c-cbb4-cad94f2a476f
* Content: [Behandlung von Installationsproblemen oder Problemen beim Upgrade - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/install/troubleshooting-installation-issues?view=vs-2019)
* Content Source: [docs/install/troubleshooting-installation-issues.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/install/troubleshooting-installation-issues.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by srvbpigh** [comment]
Hallo @klausi13:

Wir überarbeiten derzeit unseren internen Prozess und die Engineeringpipeline. Das führt leider zu Verzögerungen bei der Verarbeitung Ihres Feedbacks.

Vielen Dank für Ihren Beitrag zu unseren Artikeln und Ihr Verständnis. Wir freuen uns auf Ihre weitere Unterstützung.
