### ISSUE TITLE
mstest /testsettings runsettings config file format

### ISSUE THREAD

**Issue by fifromrs** [MicrosoftDocs/visualstudio-docs.de-de#89]
Hi

you defined the Format for the runsettings file in here:
https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019

This leads to (Just all structures made empty):
The file '...\mstest\default.runsettings' has unknown format and cannot be converted to the current version.

There is no information about "Local.runsettings". I just would like to find a simple empty Format or Format description for that content of that file. The error message is totally useless for that purpose.

Why do you not provide a download for an easy Local.runsettings and Maybe a complex one. (I just want to add one single Parameter into the TestContext.Properties to configure a set of unit Tests. And this Parameter shall be defined in the Local.runsettings. Where else?)

Best regards
fi

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e27af73d-196c-4653-aa07-acf7e8b425e3
* Version Independent ID: b8957d80-ffa0-1c42-d3f0-6e4d00bf7a1e
* Content: [Befehlszeilenoptionen für VSTest.Console.exe - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/test/vstest-console-options?view=vs-2019)
* Content Source: [docs/test/vstest-console-options.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/test/vstest-console-options.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@fifromrs Local.Runsettings is just a filename for a .runsettings file, normally set in the project root. I can clarify this in the doc. I tested TestContext.Properties using a basic .runsettings file like the following, which seems to work fine when I test it.

<?xml version="1.0" encoding="utf-8"?>

<RunSettings>
  <RunConfiguration>
    <ResultsDirectory>.\TestResults</ResultsDirectory>
  </RunConfiguration>
  <TestRunParameters>
    <Parameter name="docsUrl" value="https://docs.microsoft.com" />
  </TestRunParameters>
</RunSettings>

and this code:

private string docsUrl;
public TestContext TestContext { get; set; }

[TestMethod]
public void TestMethod1()
 {
    docsUrl = TestContext.Properties["docsUrl"].ToString();
 }

**Comment by Mikejo5000** [comment]
Updating doc

**Comment by JasonCard** [comment]
@fifromrs Thank you for your feedback.
@Mikejo5000 May have already addressed this issue, but closing here as it's been moved to [https://github.com/MicrosoftDocs/visualstudio-docs/issues/5885](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5885) as feedback for English content.
