### ISSUE TITLE
Das Tool ist nicht auffindbar

### ISSUE THREAD

**Issue by manuth** [MicrosoftDocs/visualstudio-docs.de-de#9]
Ich habe, wie im Dokument "Installieren des Visual Studio SDKs" nachzulesen, die SDK installiert und kann das Tool, welches hier thematisiert wird über die Such-Funktion von Visual Studio 2017 nicht finden.
Im gesamten Dokument wird nirgends aufgezeigt, wie und wo sich das Tool finden lässt - habe ich irgendetwas überlesen?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a79c0a5f-2226-f484-31d4-2ea98abba400
* Version Independent ID: f9356223-144a-d1d7-0715-6dcc1b05a955
* Content: [Image Bibliotheksviewer](https://docs.microsoft.com/de-de/visualstudio/extensibility/internals/image-library-viewer)
* Content Source: [docs/extensibility/internals/image-library-viewer.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/extensibility/internals/image-library-viewer.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by CeciAc** [comment]
Hallo, @manuth

vielen Dank für Ihren Beitrag. Unser Team kann nur Feedback beantworten, das sich auf die Dokumentation bezieht. 
Übermitteln Sie Feedback zu Produkten über die Schaltfläche „Feedback zu Produkten“ ganz unten auf der Dokumentationsseite. 

Wenn Sie Feedback zur Dokumentation haben, können Sie dieses gerne hier übermitteln. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team

**Comment by manuth** [comment]
Sollte sich der Weg zum Öffnen des entsprechenden Tools nicht in dessen Dokumentation befinden?
In meinen Augen macht das mehr Sinn als ein Feedback zu Visual Studio 2017 abzugeben, denn die Dokumentation ist der Ort, an dem auch andere Leute die notwendigen Schritte finden können und auch suchen würden.

Danke für die prompte Antwort

**Comment by CeciAc** [comment]
Hallo, @manuth

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation. 
Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/visualstudio-docs/issues/1091
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
