### ISSUE TITLE
Ok to suppress for TryParse

### ISSUE THREAD

**Issue by Matti-Koopa** [MicrosoftDocs/visualstudio-docs.de-de#94]
Shouldn't this rule be ok to suppress for own "TryParse"-methods? I think the article should add that.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d89b0f64-db03-af39-fdf7-ccb31c9ae01b
* Version Independent ID: 95c4aac2-4e98-240b-54e5-64981ab68cec
* Content: [CA1031: Allgemeine Ausnahmetypen nicht auffangen. - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/code-quality/ca1031?view=vs-2019)
* Content Source: [docs/code-quality/ca1031.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/code-quality/ca1031.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by JasonCard** [comment]
@Matti-Koopa Thank you for your feedback. 
Closing issue here as it's been moved to [https://github.com/MicrosoftDocs/visualstudio-docs/issues/5883](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5883) for English content.
