### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by castilma** [MicrosoftDocs/visualstudio-docs.de-de#95]
Die Seite enthält die info ```Der Knoten Allgemein ist auch sichtbar, wenn die Option Alle Einstellungen anzeigen deaktiviert ist. Wenn Sie alle verfügbaren Optionen anzeigen möchten, klicken Sie auf Alle Einstellungen anzeigen.```
Aber es ist nicht klar, wo 'Alle Einstellungen anzeigen' angeklickt werden soll.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2ad068e6-6b02-6800-e9c5-601fd7b765b7
* Version Independent ID: a7034303-7838-54a8-4c3b-cc3695e65d1d
* Content: [Verwalten von Buildkonfigurationen mit Visual Basic-Entwicklereinstellungen](https://docs.microsoft.com/de-de/visualstudio/ide/how-to-manage-build-configurations-with-visual-basic-developer-settings-applied?view=vs-2019)
* Content Source: [docs/ide/how-to-manage-build-configurations-with-visual-basic-developer-settings-applied.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/ide/how-to-manage-build-configurations-with-visual-basic-developer-settings-applied.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
The user is saying that "Show All Settings" checkbox cannot be found.  @TerryGLee - it seems that maybe there used to be a checkbox on the Tools Options dialog called "Show All Settings" but maybe it's not there anymore.  We still have docs that reference it that might need to be updated. Here's another example, https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-dialog-box-visual-studio

**Comment by JasonCard** [comment]
Closing issue as it's been moved to [https://github.com/MicrosoftDocs/visualstudio-docs/issues/5882](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5882)
